name: example
description: "An example of how to use the Serverpod Slides packages."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  slick_slides: ^0.2.0

  # Slide packages.
  get_started:
    path: ../get_started

  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # Include fonts from slick_slides package.
  fonts:
    - family: Inter
      fonts:
        - asset: packages/slick_slides/fonts/inter.ttf
    - family: JetbrainsMono
      fonts:
        - asset: packages/slick_slides/fonts/jetbrainsmono.ttf

